// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: api/chat/dialogs.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members   []string          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Meta      map[string]string `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatorId string            `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Personal  bool              `protobuf:"varint,4,opt,name=personal,proto3" json:"personal,omitempty"`
}

func (x *CreateDialogRequest) Reset() {
	*x = CreateDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDialogRequest) ProtoMessage() {}

func (x *CreateDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDialogRequest.ProtoReflect.Descriptor instead.
func (*CreateDialogRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDialogRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *CreateDialogRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CreateDialogRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateDialogRequest) GetPersonal() bool {
	if x != nil {
		return x.Personal
	}
	return false
}

type CreateDialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog *Dialog `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
}

func (x *CreateDialogResponse) Reset() {
	*x = CreateDialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDialogResponse) ProtoMessage() {}

func (x *CreateDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDialogResponse.ProtoReflect.Descriptor instead.
func (*CreateDialogResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDialogResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type UpdateDialogMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId string            `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	Meta     map[string]string `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateDialogMetaRequest) Reset() {
	*x = UpdateDialogMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDialogMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDialogMetaRequest) ProtoMessage() {}

func (x *UpdateDialogMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDialogMetaRequest.ProtoReflect.Descriptor instead.
func (*UpdateDialogMetaRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDialogMetaRequest) GetDialogId() string {
	if x != nil {
		return x.DialogId
	}
	return ""
}

func (x *UpdateDialogMetaRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateDialogMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog *Dialog `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
}

func (x *UpdateDialogMetaResponse) Reset() {
	*x = UpdateDialogMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDialogMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDialogMetaResponse) ProtoMessage() {}

func (x *UpdateDialogMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDialogMetaResponse.ProtoReflect.Descriptor instead.
func (*UpdateDialogMetaResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDialogMetaResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type GetDialogByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetDialogByIdRequest) Reset() {
	*x = GetDialogByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogByIdRequest) ProtoMessage() {}

func (x *GetDialogByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogByIdRequest.ProtoReflect.Descriptor instead.
func (*GetDialogByIdRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{4}
}

func (x *GetDialogByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDialogByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetDialogByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog *Dialog `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
}

func (x *GetDialogByIdResponse) Reset() {
	*x = GetDialogByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogByIdResponse) ProtoMessage() {}

func (x *GetDialogByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogByIdResponse.ProtoReflect.Descriptor instead.
func (*GetDialogByIdResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{5}
}

func (x *GetDialogByIdResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type GetUserDialogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OffsetId string `protobuf:"bytes,2,opt,name=offset_id,json=offsetId,proto3" json:"offset_id,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetUserDialogsRequest) Reset() {
	*x = GetUserDialogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDialogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDialogsRequest) ProtoMessage() {}

func (x *GetUserDialogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDialogsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDialogsRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserDialogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserDialogsRequest) GetOffsetId() string {
	if x != nil {
		return x.OffsetId
	}
	return ""
}

func (x *GetUserDialogsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserDialogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialogs []*Dialog `protobuf:"bytes,1,rep,name=dialogs,proto3" json:"dialogs,omitempty"`
}

func (x *GetUserDialogsResponse) Reset() {
	*x = GetUserDialogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDialogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDialogsResponse) ProtoMessage() {}

func (x *GetUserDialogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDialogsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDialogsResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserDialogsResponse) GetDialogs() []*Dialog {
	if x != nil {
		return x.Dialogs
	}
	return nil
}

type JoinDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId string `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *JoinDialogRequest) Reset() {
	*x = JoinDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinDialogRequest) ProtoMessage() {}

func (x *JoinDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinDialogRequest.ProtoReflect.Descriptor instead.
func (*JoinDialogRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{8}
}

func (x *JoinDialogRequest) GetDialogId() string {
	if x != nil {
		return x.DialogId
	}
	return ""
}

func (x *JoinDialogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type JoinDialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog *Dialog `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
}

func (x *JoinDialogResponse) Reset() {
	*x = JoinDialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinDialogResponse) ProtoMessage() {}

func (x *JoinDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinDialogResponse.ProtoReflect.Descriptor instead.
func (*JoinDialogResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{9}
}

func (x *JoinDialogResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type LeaveDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DialogId string `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LeaveDialogRequest) Reset() {
	*x = LeaveDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveDialogRequest) ProtoMessage() {}

func (x *LeaveDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveDialogRequest.ProtoReflect.Descriptor instead.
func (*LeaveDialogRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveDialogRequest) GetDialogId() string {
	if x != nil {
		return x.DialogId
	}
	return ""
}

func (x *LeaveDialogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveDialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog *Dialog `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
}

func (x *LeaveDialogResponse) Reset() {
	*x = LeaveDialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveDialogResponse) ProtoMessage() {}

func (x *LeaveDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveDialogResponse.ProtoReflect.Descriptor instead.
func (*LeaveDialogResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{11}
}

func (x *LeaveDialogResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

type CountUnreadMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CountUnreadMessagesRequest) Reset() {
	*x = CountUnreadMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountUnreadMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUnreadMessagesRequest) ProtoMessage() {}

func (x *CountUnreadMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUnreadMessagesRequest.ProtoReflect.Descriptor instead.
func (*CountUnreadMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{12}
}

func (x *CountUnreadMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CountUnreadMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadCount int64 `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
}

func (x *CountUnreadMessagesResponse) Reset() {
	*x = CountUnreadMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_chat_dialogs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountUnreadMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountUnreadMessagesResponse) ProtoMessage() {}

func (x *CountUnreadMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_dialogs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountUnreadMessagesResponse.ProtoReflect.Descriptor instead.
func (*CountUnreadMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_dialogs_proto_rawDescGZIP(), []int{13}
}

func (x *CountUnreadMessagesResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_api_chat_dialogs_proto protoreflect.FileDescriptor

var file_api_chat_dialogs_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2e, 0x63, 0x72, 0x6e, 0x74, 0x5f,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x5e,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2e,
	0x63, 0x72, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x1a, 0x37, 0x0a, 0x09, 0x4d, 0x65, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x63, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x64, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2e, 0x63, 0x72,
	0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52,
	0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0xd3, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64,
	0x12, 0x62, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4e,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69,
	0x6d, 0x2e, 0x63, 0x72, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x67, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x64, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2e, 0x63, 0x72, 0x6e,
	0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x06,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x3f, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4b, 0x0a, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69,
	0x69, 0x69, 0x6d, 0x2e, 0x63, 0x72, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x63, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x67, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x07,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d,
	0x2e, 0x63, 0x72, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x61, 0x6c,
	0x6f, 0x67, 0x52, 0x07, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x49, 0x0a, 0x11, 0x4a,
	0x6f, 0x69, 0x6e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2e,
	0x63, 0x72, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x52, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x4a, 0x0a, 0x12, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x06,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x6d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2e,
	0x63, 0x72, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x52, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x22, 0x35, 0x0a, 0x1a, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x40, 0x0a, 0x1b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4d, 0x61, 0x78, 0x69, 0x69, 0x69, 0x69, 0x69, 0x6d, 0x2f, 0x63, 0x72, 0x6e, 0x74, 0x2d,
	0x63, 0x68, 0x61, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x63, 0x68, 0x61, 0x74, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_chat_dialogs_proto_rawDescOnce sync.Once
	file_api_chat_dialogs_proto_rawDescData = file_api_chat_dialogs_proto_rawDesc
)

func file_api_chat_dialogs_proto_rawDescGZIP() []byte {
	file_api_chat_dialogs_proto_rawDescOnce.Do(func() {
		file_api_chat_dialogs_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_chat_dialogs_proto_rawDescData)
	})
	return file_api_chat_dialogs_proto_rawDescData
}

var file_api_chat_dialogs_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_chat_dialogs_proto_goTypes = []interface{}{
	(*CreateDialogRequest)(nil),         // 0: github.maxiiiiim.crnt_chat_service.api.chat.CreateDialogRequest
	(*CreateDialogResponse)(nil),        // 1: github.maxiiiiim.crnt_chat_service.api.chat.CreateDialogResponse
	(*UpdateDialogMetaRequest)(nil),     // 2: github.maxiiiiim.crnt_chat_service.api.chat.UpdateDialogMetaRequest
	(*UpdateDialogMetaResponse)(nil),    // 3: github.maxiiiiim.crnt_chat_service.api.chat.UpdateDialogMetaResponse
	(*GetDialogByIdRequest)(nil),        // 4: github.maxiiiiim.crnt_chat_service.api.chat.GetDialogByIdRequest
	(*GetDialogByIdResponse)(nil),       // 5: github.maxiiiiim.crnt_chat_service.api.chat.GetDialogByIdResponse
	(*GetUserDialogsRequest)(nil),       // 6: github.maxiiiiim.crnt_chat_service.api.chat.GetUserDialogsRequest
	(*GetUserDialogsResponse)(nil),      // 7: github.maxiiiiim.crnt_chat_service.api.chat.GetUserDialogsResponse
	(*JoinDialogRequest)(nil),           // 8: github.maxiiiiim.crnt_chat_service.api.chat.JoinDialogRequest
	(*JoinDialogResponse)(nil),          // 9: github.maxiiiiim.crnt_chat_service.api.chat.JoinDialogResponse
	(*LeaveDialogRequest)(nil),          // 10: github.maxiiiiim.crnt_chat_service.api.chat.LeaveDialogRequest
	(*LeaveDialogResponse)(nil),         // 11: github.maxiiiiim.crnt_chat_service.api.chat.LeaveDialogResponse
	(*CountUnreadMessagesRequest)(nil),  // 12: github.maxiiiiim.crnt_chat_service.api.chat.CountUnreadMessagesRequest
	(*CountUnreadMessagesResponse)(nil), // 13: github.maxiiiiim.crnt_chat_service.api.chat.CountUnreadMessagesResponse
	nil,                                 // 14: github.maxiiiiim.crnt_chat_service.api.chat.CreateDialogRequest.MetaEntry
	nil,                                 // 15: github.maxiiiiim.crnt_chat_service.api.chat.UpdateDialogMetaRequest.MetaEntry
	(*Dialog)(nil),                      // 16: github.maxiiiiim.crnt_chat_service.api.chat.Dialog
}
var file_api_chat_dialogs_proto_depIdxs = []int32{
	14, // 0: github.maxiiiiim.crnt_chat_service.api.chat.CreateDialogRequest.meta:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.CreateDialogRequest.MetaEntry
	16, // 1: github.maxiiiiim.crnt_chat_service.api.chat.CreateDialogResponse.dialog:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.Dialog
	15, // 2: github.maxiiiiim.crnt_chat_service.api.chat.UpdateDialogMetaRequest.meta:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.UpdateDialogMetaRequest.MetaEntry
	16, // 3: github.maxiiiiim.crnt_chat_service.api.chat.UpdateDialogMetaResponse.dialog:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.Dialog
	16, // 4: github.maxiiiiim.crnt_chat_service.api.chat.GetDialogByIdResponse.dialog:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.Dialog
	16, // 5: github.maxiiiiim.crnt_chat_service.api.chat.GetUserDialogsResponse.dialogs:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.Dialog
	16, // 6: github.maxiiiiim.crnt_chat_service.api.chat.JoinDialogResponse.dialog:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.Dialog
	16, // 7: github.maxiiiiim.crnt_chat_service.api.chat.LeaveDialogResponse.dialog:type_name -> github.maxiiiiim.crnt_chat_service.api.chat.Dialog
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_chat_dialogs_proto_init() }
func file_api_chat_dialogs_proto_init() {
	if File_api_chat_dialogs_proto != nil {
		return
	}
	file_api_chat_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_chat_dialogs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDialogMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDialogMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDialogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDialogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinDialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveDialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountUnreadMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_chat_dialogs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountUnreadMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_chat_dialogs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_chat_dialogs_proto_goTypes,
		DependencyIndexes: file_api_chat_dialogs_proto_depIdxs,
		MessageInfos:      file_api_chat_dialogs_proto_msgTypes,
	}.Build()
	File_api_chat_dialogs_proto = out.File
	file_api_chat_dialogs_proto_rawDesc = nil
	file_api_chat_dialogs_proto_goTypes = nil
	file_api_chat_dialogs_proto_depIdxs = nil
}
